### ISSUE TITLE
Смысл существования machine-bem-coder

### ISSUE THREAD

**Issue by tadatuta** [alexbaumgertner/presentation-bem-stack#10]
Верно ли я понимаю, что machine-bem-coder отличается от https://github.com/bem/project-stub лишь наличием gulp-конфига? Может быть схлопнуть его именно до конфига, чтобы в ридми было написано что-то вроде:
1. Склонируйте bem/project-stub
2. Положите себе этот конфиг

Тогда не будет рассинхрона (сейчас machine-bem-coder отстает от project-stub).

**Comment by alexbaumgertner** [comment]
Вроде получается так. Я проверю еще. Тогда можно в https://github.com/alexbaumgertner/machine-bem-coder только оставить package.json + gulp task/

Спасибо!

**Comment by tadatuta** [comment]
Лучше не package.json, а просто в ридми команду вида 

```
npm install список модулей
```

чтобы не руками мержить свой package.json c твоим,  а просто добавить недостающее

**Comment by alexbaumgertner** [comment]
МНЕ: подождать завершения Хакатора 12 декабря, возможно будет решено там

**Comment by alexbaumgertner** [comment]
Убрал упоминание `machine-bem-coder` из доклада, закрываю в пользу https://github.com/alexbaumgertner/machine-bem-coder/issues/9
