### ISSUE TITLE
Отзывы о рассказе в Академии

### ISSUE THREAD

**Issue by alexbaumgertner** [alexbaumgertner/presentation-bem-stack#34]

**Comment by Egenie-mih** [comment]
- [x] Может стоить заменить цвет плашки для страницы на синий? потому что этот цвет очень привлекает внимание, а номер страницы не так важен, в отличие от слайда.
- [x]  Может сделать ссылки на презентации и видео других докладов в самом конце? Ведь у тебя доклад свой, и основная информация должна быть сделана тобой)
- [ ] Могу помочь с картиками-скриншотами. Чтобы качество было лучше. А то на этом эране они не особо хорошо смотрелись, а на большем будет хуже.
- [x] Если идут плашки на большинстве страницах, то лучше пусть они будут одинаковыми на всех страницах) Квадратики в правом верхнем углу.
  слайды:
- [x]  рябит в глазах это слово)
- [x]  Либо делать пунктами (без«и»), либо предложениями. А вообще может так?
  Методология БЭМ.
  – проектировании;
  – реализации;
  – сопровождении проекта.
- [x]  запятая: BEMJSON – тип данных, в котором выражается:
   точка: вспомогательные данные.
- [x]  гибкое переопределение поведениЯ
- [x] затемни фоновую картинку, лучше будет читаться текст

**Comment by alexbaumgertner** [comment]
Внес все правки http://alexbaumgertner.github.io/presentation-bem-stack/
С картинками, надо ретина дисплей, чтобы в хорошем разрешении их вырезать.

Спасибо большое!
