### ISSUE TITLE
Добавить сравнение шаблонизаторов React и BEM-stack

### ISSUE THREAD

**Issue by ilyar** [alexbaumgertner/presentation-bem-stack#40]
Будет полезно добавить сравнение шаблонизаторов React и BEM-stack, для раскрытия вопроса будет полезен комментарий https://github.com/bem/bem-forum-content-ru/issues/891#issuecomment-189616842

**Comment by alexbaumgertner** [comment]
Спасибо, постараюсь на неделе посмотреть.
Самое главное, производительность измерить, как я понял :)

**Comment by ilyar** [comment]
Конечно, производительность может быть решающим фактором в выборе технологии, но не всегда, а потом не всегда можно объективно это сравнить.

Будет действительно полезно сравнить практической точки зрения один кейс с нарастающей сложность с приходом новых требований, как это бывает в реальных проектах, и возможное решения в  React и BEM-stack.

**Comment by alexbaumgertner** [comment]
Помощь и список вопросов для сравнения приветствуется :)
