### ISSUE TITLE
Online-demo bem-xjst

### ISSUE THREAD

**Issue by tadatuta** [alexbaumgertner/presentation-bem-stack#7]
Важно понимать, что BEM-XJST online demo использует данные, которые закэшировались в браузере, поэтому, нельзя рассчитывать, что у того, кто смотрит презентацию, там окажется тот же код, что и у тебя.

**Comment by alexbaumgertner** [comment]
Да, надо подумать, как делать этот слайд, спасибо!

**Comment by alexbaumgertner** [comment]
Оставил только ссылку на сайт
