### ISSUE TITLE
BEMTREE

### ISSUE THREAD

**Issue by tadatuta** [alexbaumgertner/presentation-bem-stack#8]
1. В ближайшее время в bem-xjst 4 появится поддержка BEMTREE, но пока синхронная (см. https://github.com/bem/bem-xjst/pull/132)
2. У нас есть дока https://ru.bem.info/technology/bemtree/v2/bemtree/ но в ней пока никак не отражено [1]
3. Есть репо https://github.com/tadatuta/bem-express где используется настроенная связка из нового BEMTREE -> BEMHTML на express

**Comment by alexbaumgertner** [comment]
Закрою в пользу https://github.com/alexbaumgertner/presentation-bem-stack/issues/39
